const CONST = {
    CATEGORY_TO_KOR: {
        accounting: '회계사',
        airport: '공항',
        amusement_park: '유원지',
        aquarium: '수족관',
        art_gallery: '미술 갤러리',
        atm: 'ATM기',
        bakery: '빵집',
        bank: '은행',
        bar: '바',
        beauty_salon: '미용실',
        bicycle_store: '자전거 가게',
        book_store: '서점',
        bowling_alley: '볼링장',
        bus_station: '버스 정류장',
        cafe: '카페',
        campground: '캠핑장',
        car_dealer: '자동차 딜러',
        car_rental: '렌터카',
        car_repair: '자동차 수리소',
        car_wash: '세차장',
        casino: '카지노',
        cemetery: '묘지',
        church: '교회',
        city_hall: '시청',
        clothing_store: '의류 매장',
        convenience_store: '편의점',
        courthouse: '법원',
        dentist: '치과 의사',
        department_store: '백화점',
        doctor: '의사',
        drugstore: '약국',
        electrician: '전기 기술자',
        electronics_store: '전자제품 매장',
        embassy: '대사관',
        fire_station: '소방서',
        florist: '꽃집',
        funeral_home: '장례식장',
        furniture_store: '가구 매장',
        gas_station: '주유소',
        gym: '헬스장',
        hair_care: '미용실',
        hardware_store: '철물점',
        hindu_temple: '힌두 사원',
        home_goods_store: '생활용품 매장',
        hospital: '병원',
        insurance_agency: '보험 에이전시',
        jewelry_store: '보석점',
        laundry: '세탁소',
        lawyer: '변호사',
        library: '도서관',
        light_rail_station: '전철 정거장',
        liquor_store: '주류 매장',
        local_government_office: '지방 정부 사무실',
        locksmith: '자물쇠장',
        lodging: '숙박 시설',
        meal_delivery: '식사 배달',
        meal_takeaway: '포장 식사',
        mosque: '모스크',
        movie_rental: '영화 대여',
        movie_theater: '영화관',
        moving_company: '이사회사',
        museum: '박물관',
        night_club: '나이트 클럽',
        painter: '화가',
        park: '공원',
        parking: '주차장',
        pet_store: '애완 동물 가게',
        pharmacy: '약국',
        physiotherapist: '물리치료사',
        plumber: '배관공',
        police: '경찰서',
        post_office: '우체국',
        primary_school: '초등학교',
        real_estate_agency: '부동산 에이전시',
        restaurant: '레스토랑',
        roofing_contractor: '지붕 공사업자',
        rv_park: '캠핑장',
        school: '학교',
        secondary_school: '중학교',
        shoe_store: '신발가게',
        shopping_mall: '쇼핑몰',
        spa: '스파',
        stadium: '경기장',
        storage: '보관 시설',
        store: '가게',
        subway_station: '지하철 역',
        supermarket: '슈퍼마켓',
        synagogue: '유대교회',
        taxi_stand: '택시 스탠드',
        tourist_attraction: '관광 명소',
        train_station: '기차역',
        transit_station: '트랜짓 스테이션',
        travel_agency: '여행사',
        university: '대학교',
        veterinary_care: '수의원',
        zoo: '동물원',
    },
};

export default CONST;
