export const TYPE = {
    // 모달
    OPEN_POPUP_MODAL: 'OPEN_POPUP_MODAL',
    CLOSE_POPUP_MODAL: 'CLOSE_POPUP_MODAL',
    OPEN_SLIDE_MODAL: 'OPEN_SLIDE_MODAL',
    CLOSE_SLIDE_MODAL: 'CLOSE_SLIDE_MODAL',
};
